house_cleaning/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  devise_for :users
  resources :cleaners

  root to: "pedidos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

house_cleaning/app/models/cleaner.rb
class Cleaner < ApplicationRecord
    belongs_to :user
end

house_cleaning/app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
  before_action :set_cleaner, only: [:show, :edit, :update, :destroy]

  # GET /cleaners
  # GET /cleaners.json
  def index
    @cleaners = Cleaner.all
  end

  # GET /cleaners/1
  # GET /cleaners/1.json
  def show
  end

  # GET /cleaners/new
  def new
    @cleaner = current_user.cleaners.build
  end

  # GET /cleaners/1/edit
  def edit
  end

  # POST /cleaners
  # POST /cleaners.json
  def create
    @cleaner = current_user.cleaners.build(cleaner_params)

    respond_to do |format|
      if @cleaner.save
        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully created.' }
        format.json { render :show, status: :created, location: @cleaner }
      else
        format.html { render :new }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cleaners/1
  # PATCH/PUT /cleaners/1.json
  def update
    respond_to do |format|
      if @cleaner.update(cleaner_params)
        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully updated.' }
        format.json { render :show, status: :ok, location: @cleaner }
      else
        format.html { render :edit }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cleaners/1
  # DELETE /cleaners/1.json
  def destroy
    @cleaner.destroy
    respond_to do |format|
      format.html { redirect_to cleaners_url, notice: 'Cleaner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cleaner
      @cleaner = Cleaner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cleaner_params
      params.require(:cleaner).permit(:nome, :idade, :dias_disponiveis, :servicos, :pedido_id, :user_id)
    end
end

house_cleaning/app/helpers/cleaners_helper.rb
module CleanersHelper
end

house_cleaning/app/views/cleaners/_form.html.erb
<%= form_with(model: cleaner, local: true) do |form| %>
  <% if cleaner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cleaner.errors.count, "error") %> prohibited this cleaner from being saved:</h2>

      <ul>
        <% cleaner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <font size="5"><%= form.label :nome%>
    <%= form.text_field :nome, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger", value:"Marinete #{rand 100}"  %>
    </font>
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :servicos %>
    <%= form.text_field :servicos, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
    </font>
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :dias_disponiveis %>
    <%= form.number_field :dias_disponiveis, max: 5, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
    </font>  
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :idade %>
    <%= form.number_field :idade, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
    </font>  
  </div>

  <div class="form-group">
    <font size="5"><%= form.submit "Salvar", class: "btn btn-lg btn-primary" %></font>
  </div>
<% end %>

house_cleaning/app/views/cleaners/edit.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
<h1>Editing Cleaner</h1>

<%= render 'form', cleaner: @cleaner %>

<%= link_to 'Mostrar', @cleaner, class:"btn btn-lg btn-primary" %> 
<%= link_to 'Voltar', cleaners_path, class:"btn btn-lg btn-primary" %>

house_cleaning/app/views/cleaners/index.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>


<h1>Faxineiras</h1>

<% @cleaners.each do |cleaner| %>
  <div class="cleaner row clearfix">
    <%if current_user.cleaners.include?(cleaner)%>
      <td><font size="5"><%= link_to cleaner.nome , cleaner, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></td></font>
    <%end%>
    <small class="cleaner"></small>
 </div>
<% end %>

house_cleaning/app/views/cleaners/new.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
<h1>Pedir faxineira</h1>

<%= render 'form', cleaner: @cleaner %>

<%= link_to 'Voltar', root_path %>

house_cleaning/app/views/cleaners/show.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>

<p id="notice"><%= notice %></p>
<h1>Faxineira</h1>
<div class="page-header">
  <td><font size="5"><strong>Nome: <%= @cleaner.nome %></strong></td></font>  
  <br>  
  <td><font size="5"><strong>Idade: <%= @cleaner.idade %></strong></td></font>
</div>

<% if user_signed_in? %>
	<div class="btn-group">
		<%= link_to 'Voltar para pedidos', root_path, class:"btn btn-lg btn-primary"%>
          <%= link_to 'Voltar para faxineiras', cleaners_path, class:"btn btn-lg btn-primary"%>
		<%= link_to 'Editar', edit_cleaner_path(@cleaner), class:"btn btn-lg btn-primary" %>
		<%= link_to 'Deletar', @cleaner, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-lg btn-primary" %>
	</div>
<% end %>