house_cleaning/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  devise_for :users
  resources :cleaners

  root to: "pedidos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

house_cleaning/app/models/pedido.rb
class Pedido < ApplicationRecord
    belongs_to :user
end

house_cleaning/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = current_user.pedidos.find(params[:id])
    @pedido.preco = @pedido.numero_dias * 100
  end

  # GET /pedidos/new
  def new
    @pedido = current_user.pedidos.build
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = current_user.pedidos.build(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:nome, :local, :numero_dias, :exigencias, :preco, :cleaner_id)
    end
end

house_cleaning/app/helpers/pedidos_helper.rb
module PedidosHelper
end

house_cleaning/app/views/pedidos/_form.html.erb
<%= form_with(model: pedido, local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>
      <ul>
        <% pedido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <font size="5"><%= form.label :nome %>
    <%= form.text_field :nome ,  class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
    </font>
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :local %>
    <%= form.text_field :local ,  class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
    </font> 
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :numero_dias %>
    <%= form.number_field :numero_dias, max: 5 ,  class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
    </font> 
  </div>

  <div class="form-group">
    <font size="5"><%= form.label :exigencias %>
    <%= form.text_field :exigencias,  class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
    </font>
  </div>

  <div class="form-group">
    <font size="10"><%= form.submit "Salvar", class: "btn btn-lg btn-primary" %></font>
  </div>
  
<% end %>

house_cleaning/app/views/pedidos/edit.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>
<% if user_signed_in?%>
    
    
    <td><%= link_to 'Editar', edit_pedido_path(@pedido), class: "btn bnt-lg btn-primary" %></td>
    <td><%= link_to 'Deletar', @pedido, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn bnt-lg btn-primary" %></td>
<% end %>

<%= link_to 'Mostrar', @pedido, class: "btn bnt-lg btn-primary" %> 
<%= link_to 'Voltar', pedidos_path, class: "btn bnt-lg btn-primary" %>

house_cleaning/app/views/pedidos/index.html.erb
<!DOCTYPE html>
<html>
<br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
      <br>
      <br>
<head>
    <title>Pedidos</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'freelancer', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    </head>
<body>
<%if user_signed_in?%>
  <h1>Pedidos</h1>

    <div>

    </div>
    <% @pedidos.each do |pedido| %>
      <% if current_user == pedido.user%>
        <div class="cleaner row clearfix">
            <td><font size="5"><%= link_to pedido.nome, pedido, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></font></td>
        </div>
      <% end %>
    <% end %>
<%else%>

<div class="container d-flex align-items-center flex-column">

      <!-- Masthead Avatar Image -->
      <img class="masthead-avatar mb-5" src="assets/images/avataaars.svg" alt="">

      <!-- Masthead Heading -->
      <h1 class="masthead-heading text-uppercase mb-0">HouseCleaning</h1>

      <!-- Icon Divider -->
      <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>

      <!-- Masthead Subheading -->
<p class="lead">For your house, for your life.</p>

    <br>
    <br>
    <br>
    <br>

    </div>


  <section class="page-section bg-primary text-white mb-0" id="about" >
    <div class="container">

      <!-- About Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>

      <!-- Icon Divider -->
      <div class="divider-custom divider-light">
              <div class="divider-custom-line"></div>
              <div class="divider-custom-icon">

              </div>
              <div class="divider-custom-line"></div>
            </div>

      <!-- About Section Content -->
      <div class="row">
        <div class="col-lg-4 ml-auto">
          <p class="lead">HouseCleaning is a website that you can have a diferenciated clean at your house. With professionals services, your house will be the perfect house.</p>
        </div>
        <div class="col-lg-4 mr-auto">
          <p class="lead">HouseCleaning é um site em que você pode ter uma limpeza diferenciada em sua casa. Com serviços profissionais, sua casa será a casa perfeita.</p>
        </div>
      </div>

      <!-- About Section Button -->
  <!--    <div class="text-center mt-4">
        <a class="btn btn-xl btn-outline-light" href="https://startbootstrap.com/themes/freelancer/">
          <i class="fas fa-download mr-2"></i>
          Free Download!
        </a>
      </div>
-->
    </div>
  </section>

<%end%>
<br>
</body>
</html>

house_cleaning/app/views/pedidos/new.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
<h1>Novo Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Voltar', pedidos_path, class:"btn btn-lg btn-primary" %>

house_cleaning/app/views/pedidos/show.html.erb
 <br>
      <br>
      <br>
      <br>
       <br>
      <br>
      <br>
      <br>

 <br>
      <br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pedido.nome %>
</p>

<p>
  <strong>Local:</strong>
  <%= @pedido.local %>
</p>

<p>
  <strong>Numero dias:</strong>
  <%= @pedido.numero_dias %>
</p>

<p>
  <strong>Exigencias:</strong>
  <%= @pedido.exigencias %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @pedido.preco %>
</p>


<% if @pedido.user == current_user %>
  <div class="form-group">
         <% if current_user.cleaners.any?%>
            <%= link_to "Mostrar Faxineira", current_user.cleaners.last, class: "btn btn-lg btn-primary"%>
         <% else %>
            <%= link_to "Adicionar Faxineira", new_cleaner_path, class: "btn btn-lg btn-primary"%>
         <% end %>
  </div>
  <%= link_to 'Editar', edit_pedido_path(@pedido), class: "btn btn-lg btn-primary" %> |
  <%= link_to 'Voltar', pedidos_path, class: "btn btn-lg btn-primary" %>
<% end %>