house_cleaning/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  devise_for :users
  resources :cleaners

  root to: "pedidos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

house_cleaning/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseCleaning</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'freelancer', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="#page-top">HouseCleaning</a>
          <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
         
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Listar Faxineiras', cleaners_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Listar Pedidos', pedidos_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Pedido de faxina', new_pedido_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
              
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to current_user.email , edit_user_registration_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%></li>
              <%else%>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Registrar-se', new_user_registration_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to 'Login', new_user_session_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
              </li>
               
              <%end%>
            </ul>
          </div>
        </div>
      </nav>



	<%# <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
      <div id="logo" class="navbar-brand"><%= link_to "House Cleaning", root_path</div>
        <%# <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <% if user_signed_in? %>
          <%# <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Listar faxineiras', cleaners_path</li>
            <%# <li><%= link_to 'Pedido de faxina', new_pedido_path</li> %>
            <%# <li><%= link_to 'Editar perfil', edit_user_registration_path</li> %>
            <%# <strong><%= current_user.email</strong>  %>
            <%# <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete</li> %>
          <%# </ul> %>
        <%# <% else %>
        <%# <ul class="nav navbar-nav pull-right"> %>
          <%# <li><%= link_to "Registrar-se", new_user_registration_path</li> %>
          <%# <li><%= link_to "Login", new_user_session_path</li> %>
        <%# </ul> %>
        <%# <% end %> 

        <%# <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/ideas">Ideas</a>
          </li>
        </ul> %>
        <%# </nav> %>
      <%# </div>
    </div>
  </header> %>

    <div id="main_content" class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
        <div id="content" class="col-md-9 center-block">
          <%= yield %>
        </div>
      </div>
	  </div>
    
      <footer class="copyright py-4 text-center text-white" >
        <div class="container">
          <small>Copyright © HouseCleaning 2019</small>
        </div>
      </footer>
    </div>

  </body>
</html>